---
- name: Playbook
  hosts: webservers
  become: yes
  become_user: root
  tasks:
    - name: ensure apache is at latest version
      apt:
        name: httpd
        state: latest
    - name: ensure apache is running
      service:
        name: httpd
        state: started