apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: addressbook 
  labels:  
    app: addressbook  
spec:  
  replicas: 4  
  selector:  
    matchLabels:  
      app: addressbook  
  template:  
    metadata:  
      labels:  
        app: addressbook  
    spec:  
      containers:  
      - name: addressbook  
        image: devopsmvc/addressbook:1.0  
        ports:  
        - containerPort: 8080
