apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: springboot-demo 
  labels:  
    app: springboot-demo  
spec:  
  replicas: 4  
  selector:  
    matchLabels:  
      app: springboot-demo  
  template:  
    metadata:  
      labels:  
        app: springboot-demo  
    spec:  
      containers:  
      - name: springboot-demo  
        image: devopsmvc/springboot-demo:1.0  
        ports:  
        - containerPort: 8080
